# Generated by Django 2.2 on 2019-06-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=64)),
                ('Username', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=64)),
                ('Membership_type', models.CharField(max_length=64)),
                ('Booking_id', models.IntegerField()),
            ],
        ),
    ]
