# Generated by Django 2.2 on 2019-06-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel3', '0003_auto_20190610_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platinum',
            name='Room_id',
        ),
    ]
