# Generated by Django 2.2 on 2019-06-11 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel3', '0004_remove_platinum_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platinum',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel3.Register'),
        ),
    ]
