# Generated by Django 2.2 on 2019-06-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel3', '0005_auto_20190611_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platinum',
            name='Room_number',
            field=models.CharField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105')], max_length=64),
        ),
    ]
