# Generated by Django 2.2 on 2019-06-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel3', '0007_platinum_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platinum',
            old_name='Room_id',
            new_name='Booking_id',
        ),
    ]
