# Generated by Django 2.2 on 2019-06-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel3', '0008_auto_20190611_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platinum',
            name='Booking_id',
        ),
    ]
