# Generated by Django 2.2 on 2019-06-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel3', '0009_remove_platinum_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platinum',
            name='Booking_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
