# Generated by Django 2.2 on 2019-06-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel3', '0010_platinum_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platinum',
            name='Check_In',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='platinum',
            name='Check_Out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
