# Generated by Django 2.2 on 2019-06-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel3', '0012_auto_20190611_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='platinum',
            name='Room_type',
            field=models.CharField(choices=[('Premium1', 'Premium'), ('Non-premium2', 'Non-premium')], default=2, max_length=64),
            preserve_default=False,
        ),
    ]
