# Generated by Django 2.2 on 2019-06-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel3', '0014_auto_20190611_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Booking_id',
            new_name='Booking1_id',
        ),
    ]
